name: Rust

on:
  push:
    branches: "**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Init
      run: make init
    - name: Build
      run: make build
    - name: Run tests
      run: make test

